backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - label: "Pages (nl)"
    name: "pages-nl"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        format: 'json'
        file: "assets/content/pages/nl/home.json"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        format: 'json'
        file: "assets/content/pages/nl/contact.json"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - label: "Lid worden"
        name: "lid-worden"
        format: 'json'
        file: "assets/content/pages/nl/lid-worden.json"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - label: "Vrijwilligers"
        name: "vrijwilligers"
        format: 'json'
        file: "assets/content/pages/nl/vrijwilligers.json"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
  - label: "Pages (en)"
    name: "pages-en"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        format: 'json'
        file: "assets/content/pages/en/home.json"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        format: 'json'
        file: "assets/content/pages/en/contact.json"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - label: "Lid worden"
        name: "lid-worden"
        format: 'json'
        file: "assets/content/pages/nl/lid-worden.json"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
      - label: "Vrijwilligers"
        name: "vrijwilligers"
        format: 'json'
        file: "assets/content/pages/nl/vrijwilligers.json"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Tekst", name: "body", widget: "markdown"}
