backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }

  - label: "Pages en"
    create: true
    filter: {field: "language", value: "nl"}
    name: "page-nl"
    folder: "assets/content"
    format: 'json'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Pages nl"
    create: true
    filter: {field: "language", value: "en"}
    name: "page-en"
    folder: "assets/content"
    format: 'json'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
